services:
  laravel:
    image: games-laravel-dev
    # image: games-laravel-prod
    container_name: games_laravel
    volumes:
      - ./:/var/www/html
    ports:
      - "80"
    depends_on:
      - database
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=games_database
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - network

  database:
    image: mysql:8.0
    container_name: games_database
    ports:
      - "5000:3306"
    environment:
      MYSQL_DATABASE: game_website
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - network

  redis:
    image: redis:latest
    container_name: games_redis
    ports:
      - "6379:6379"
    command: [ "redis-server" ]
    networks:
      - network

volumes:
  mysql-data:


networks:
  network:
    driver: bridge
